Update connman config
- keep original user=root dbus policy
- adjust wpa_supplicant to be similar to the original one
- bump release

Now you need to add group wheel policy manually

diff --git a/connman/connmand b/connman/connmand
--- a/connman/connmand
+++ b/connman/connmand
@@ -2,20 +2,35 @@
 #
 # /etc/rc.d/connamnd: start/stop connman daemon
 #
-NAME="/usr/sbin/connmand"
+
+SSD=/sbin/start-stop-daemon
+PROG=/usr/sbin/connmand
+PID=/run/connmand.pid
+
+
 case $1 in
-start)
-	$NAME
-	;;
-stop)
-	/usr/bin/killall -e $NAME
-	;;
-restart)
-	$0 stop
-	sleep 2
-	$0 start
-	;;
-*)
-	echo "usage: $0 [start|stop|restart]"
-	;;
+	start)
+		$SSD --start --pidfile $PID --exec $PROG -- $OPTS
+		;;
+	stop)
+		$SSD --stop --retry 10 --pidfile $PID
+		;;
+	restart)
+		$0 stop
+		$0 start
+		;;
+	status)
+		$SSD --status --pidfile $PID
+		case $? in
+		0) echo "$PROG is running with pid $(cat $PID)" ;;
+		1) echo "$PROG is not running but the pid file $PID exists" ;;
+		3) echo "$PROG is not running" ;;
+		4) echo "Unable to determine the program status" ;;
+		esac
+		;;
+	*)
+		echo "Usage: $0 [start|stop|restart|status]"
+		;;
 esac
+
+# End of file
